#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PROFILE="${PROFILE:-fast}"
TARGET_REPO="${TARGET_REPO:-}"
TARGET_LANE="${TARGET_LANE:-}"

echo "== Governance profile: ${PROFILE} =="
if [[ -n "$TARGET_REPO" ]]; then
  echo "Target repo: ${TARGET_REPO}"
fi
if [[ -n "$TARGET_LANE" ]]; then
  echo "Target lane: ${TARGET_LANE}"
fi

# Defaults for minimal PR-safe checks.
RUN_PORTFOLIO_STATUS="${RUN_PORTFOLIO_STATUS:-0}"
RUN_REMOTE_COLLISIONS="${RUN_REMOTE_COLLISIONS:-0}"
RUN_REVIEW_GATE="${RUN_REVIEW_GATE:-0}"
RUN_SCOPE_CHECK="${RUN_SCOPE_CHECK:-1}"
RUN_PORTFOLIO_READINESS_CHECK="${RUN_PORTFOLIO_READINESS_CHECK:-0}"
RUN_MOBILE_GOVERNANCE_CHECK="${RUN_MOBILE_GOVERNANCE_CHECK:-0}"
RUN_RUNTIME_DISCLOSURE_DRIFT_CHECK="${RUN_RUNTIME_DISCLOSURE_DRIFT_CHECK:-0}"
RUN_ARCH_SCALE_FIT_CHECK="${RUN_ARCH_SCALE_FIT_CHECK:-1}"

case "$PROFILE" in
  fast)
    # Keep fast defaults; allow caller overrides via env vars.
    ;;
  pm-portal)
    RUN_MOBILE_GOVERNANCE_CHECK="${RUN_MOBILE_GOVERNANCE_CHECK:-1}"
    RUN_RUNTIME_DISCLOSURE_DRIFT_CHECK="${RUN_RUNTIME_DISCLOSURE_DRIFT_CHECK:-1}"
    ;;
  release)
    RUN_PORTFOLIO_STATUS="${RUN_PORTFOLIO_STATUS:-1}"
    RUN_REMOTE_COLLISIONS="${RUN_REMOTE_COLLISIONS:-1}"
    RUN_PORTFOLIO_READINESS_CHECK="${RUN_PORTFOLIO_READINESS_CHECK:-1}"
    RUN_MOBILE_GOVERNANCE_CHECK="${RUN_MOBILE_GOVERNANCE_CHECK:-1}"
    RUN_RUNTIME_DISCLOSURE_DRIFT_CHECK="${RUN_RUNTIME_DISCLOSURE_DRIFT_CHECK:-1}"
    RUN_ARCH_SCALE_FIT_CHECK="${RUN_ARCH_SCALE_FIT_CHECK:-1}"
    ;;
  full)
    RUN_PORTFOLIO_STATUS="${RUN_PORTFOLIO_STATUS:-1}"
    RUN_REMOTE_COLLISIONS="${RUN_REMOTE_COLLISIONS:-1}"
    RUN_SCOPE_CHECK="${RUN_SCOPE_CHECK:-1}"
    RUN_PORTFOLIO_READINESS_CHECK="${RUN_PORTFOLIO_READINESS_CHECK:-1}"
    RUN_MOBILE_GOVERNANCE_CHECK="${RUN_MOBILE_GOVERNANCE_CHECK:-1}"
    RUN_RUNTIME_DISCLOSURE_DRIFT_CHECK="${RUN_RUNTIME_DISCLOSURE_DRIFT_CHECK:-1}"
    RUN_ARCH_SCALE_FIT_CHECK="${RUN_ARCH_SCALE_FIT_CHECK:-1}"
    ;;
  *)
    echo "Unknown PROFILE=${PROFILE}. Expected: fast|pm-portal|release|full"
    exit 2
    ;;
esac

export RUN_PORTFOLIO_STATUS
export RUN_REMOTE_COLLISIONS
export RUN_REVIEW_GATE
export RUN_SCOPE_CHECK
export RUN_PORTFOLIO_READINESS_CHECK
export RUN_MOBILE_GOVERNANCE_CHECK
export RUN_RUNTIME_DISCLOSURE_DRIFT_CHECK
export RUN_ARCH_SCALE_FIT_CHECK

python3 scripts/render_governance_summary.py
bash scripts/run_pm_governance_sweep.sh
